### ISSUE TITLE
PEP8

### ISSUE THREAD

**Issue by antosha417** [Geelay/prog_Kuz#6]
Пользуйся pylint или пайчармом или https://github.com/spyder-ide/spyder-autopep8
Поправь код так, чтоб у меня не пайчарм ничего не подчёркивал.
Это никуда не годится
![Плохой код](https://user-images.githubusercontent.com/14187674/47442000-2a65be80-d7ba-11e8-892a-0de65a7f1a99.png)

**Comment by Geelay** [comment]
@antosha417 поправил
